package GUI;

import Model.Baraja;
import Model.Juego;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Charlie
 */
public class MainWindow extends javax.swing.JFrame {

    private Juego juegoActual;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        setLocationRelativeTo(null);
        juegoActual = new Juego(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        porcentajeArr = new javax.swing.JLabel();
        porcentajeArrIzda = new javax.swing.JLabel();
        porcentajeArrDcha = new javax.swing.JLabel();
        porcentajeAbDcha = new javax.swing.JLabel();
        porcentajeAb = new javax.swing.JLabel();
        porcentajeAbIzda = new javax.swing.JLabel();
        jLabelTurn = new javax.swing.JLabel();
        jLabelFlop3 = new javax.swing.JLabel();
        jLabelFlop2 = new javax.swing.JLabel();
        jLabelFlop1 = new javax.swing.JLabel();
        jLabelRiver = new javax.swing.JLabel();
        jLabelArribaDcha1 = new javax.swing.JLabel();
        jLabelArribaDcha2 = new javax.swing.JLabel();
        jLabelArriba2 = new javax.swing.JLabel();
        jLabelArriba1 = new javax.swing.JLabel();
        jLabelArribaIzda1 = new javax.swing.JLabel();
        jLabelArribaIzda2 = new javax.swing.JLabel();
        jLabelAbajoDcha2 = new javax.swing.JLabel();
        jLabelAbajoDcha1 = new javax.swing.JLabel();
        jLabelAbajo2 = new javax.swing.JLabel();
        jLabelAbajo1 = new javax.swing.JLabel();
        jLabelAbajoIzda2 = new javax.swing.JLabel();
        jLabelAbajoIzda1 = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jButtonAleatorio = new javax.swing.JButton();
        jButtonPreflop = new javax.swing.JButton();
        jButtonFlop = new javax.swing.JButton();
        jButtonRiver = new javax.swing.JButton();
        jButtonTurn = new javax.swing.JButton();
        foldJugArr = new javax.swing.JButton();
        foldJugArrIzda = new javax.swing.JButton();
        foldJugArrDcha = new javax.swing.JButton();
        foldJugAb = new javax.swing.JButton();
        foldJugAbIzda = new javax.swing.JButton();
        foldJugAbDcha = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Las equities guapas en Comic Sans");
        setMinimumSize(new java.awt.Dimension(1200, 900));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        porcentajeArr.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        getContentPane().add(porcentajeArr, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 80, 40));

        porcentajeArrIzda.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        getContentPane().add(porcentajeArrIzda, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 80, 40));

        porcentajeArrDcha.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        getContentPane().add(porcentajeArrDcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 140, 80, 40));

        porcentajeAbDcha.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        getContentPane().add(porcentajeAbDcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 550, 80, 40));

        porcentajeAb.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        getContentPane().add(porcentajeAb, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, 80, 40));

        porcentajeAbIzda.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        getContentPane().add(porcentajeAbIzda, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 80, 40));

        jLabelTurn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Repr Cartas/red_joker.jpg"))); // NOI18N
        jLabelTurn.setMaximumSize(new java.awt.Dimension(145, 100));
        jLabelTurn.setMinimumSize(new java.awt.Dimension(145, 100));
        jLabelTurn.setPreferredSize(new java.awt.Dimension(145, 100));
        jLabelTurn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTurnMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 100, 145));

        jLabelFlop3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Repr Cartas/red_joker.jpg"))); // NOI18N
        jLabelFlop3.setMaximumSize(new java.awt.Dimension(145, 100));
        jLabelFlop3.setMinimumSize(new java.awt.Dimension(145, 100));
        jLabelFlop3.setPreferredSize(new java.awt.Dimension(145, 100));
        jLabelFlop3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFlop3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelFlop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 100, 145));

        jLabelFlop2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Repr Cartas/red_joker.jpg"))); // NOI18N
        jLabelFlop2.setMaximumSize(new java.awt.Dimension(145, 100));
        jLabelFlop2.setMinimumSize(new java.awt.Dimension(145, 100));
        jLabelFlop2.setPreferredSize(new java.awt.Dimension(145, 100));
        jLabelFlop2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFlop2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelFlop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 100, 145));

        jLabelFlop1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Repr Cartas/red_joker.jpg"))); // NOI18N
        jLabelFlop1.setMaximumSize(new java.awt.Dimension(145, 100));
        jLabelFlop1.setMinimumSize(new java.awt.Dimension(145, 100));
        jLabelFlop1.setPreferredSize(new java.awt.Dimension(145, 100));
        jLabelFlop1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFlop1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelFlop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 100, 145));

        jLabelRiver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Repr Cartas/red_joker.jpg"))); // NOI18N
        jLabelRiver.setMaximumSize(new java.awt.Dimension(145, 100));
        jLabelRiver.setMinimumSize(new java.awt.Dimension(145, 100));
        jLabelRiver.setPreferredSize(new java.awt.Dimension(145, 100));
        jLabelRiver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRiverMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelRiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, 100, 145));

        jLabelArribaDcha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Repr Cartas/red_joker.jpg"))); // NOI18N
        jLabelArribaDcha1.setText("jLabel2");
        jLabelArribaDcha1.setMaximumSize(new java.awt.Dimension(145, 100));
        jLabelArribaDcha1.setMinimumSize(new java.awt.Dimension(145, 100));
        jLabelArribaDcha1.setPreferredSize(new java.awt.Dimension(145, 100));
        jLabelArribaDcha1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelArribaDcha1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelArribaDcha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 190, 100, 145));

        jLabelArribaDcha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Repr Cartas/red_joker.jpg"))); // NOI18N
        jLabelArribaDcha2.setText("jLabel2");
        jLabelArribaDcha2.setMaximumSize(new java.awt.Dimension(145, 100));
        jLabelArribaDcha2.setMinimumSize(new java.awt.Dimension(145, 100));
        jLabelArribaDcha2.setPreferredSize(new java.awt.Dimension(145, 100));
        jLabelArribaDcha2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelArribaDcha2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelArribaDcha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 190, 100, 145));

        jLabelArriba2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Repr Cartas/red_joker.jpg"))); // NOI18N
        jLabelArriba2.setMaximumSize(new java.awt.Dimension(145, 100));
        jLabelArriba2.setMinimumSize(new java.awt.Dimension(145, 100));
        jLabelArriba2.setPreferredSize(new java.awt.Dimension(145, 100));
        jLabelArriba2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelArriba2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelArriba2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 100, 145));

        jLabelArriba1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Repr Cartas/red_joker.jpg"))); // NOI18N
        jLabelArriba1.setText("jLabel2");
        jLabelArriba1.setMaximumSize(new java.awt.Dimension(145, 100));
        jLabelArriba1.setMinimumSize(new java.awt.Dimension(145, 100));
        jLabelArriba1.setPreferredSize(new java.awt.Dimension(145, 100));
        jLabelArriba1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelArriba1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelArriba1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 100, 145));

        jLabelArribaIzda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Repr Cartas/red_joker.jpg"))); // NOI18N
        jLabelArribaIzda1.setText("jLabel2");
        jLabelArribaIzda1.setMaximumSize(new java.awt.Dimension(145, 100));
        jLabelArribaIzda1.setMinimumSize(new java.awt.Dimension(145, 100));
        jLabelArribaIzda1.setPreferredSize(new java.awt.Dimension(145, 100));
        jLabelArribaIzda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelArribaIzda1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelArribaIzda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 100, 145));

        jLabelArribaIzda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Repr Cartas/red_joker.jpg"))); // NOI18N
        jLabelArribaIzda2.setText("jLabel2");
        jLabelArribaIzda2.setMaximumSize(new java.awt.Dimension(145, 100));
        jLabelArribaIzda2.setMinimumSize(new java.awt.Dimension(145, 100));
        jLabelArribaIzda2.setPreferredSize(new java.awt.Dimension(145, 100));
        jLabelArribaIzda2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelArribaIzda2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelArribaIzda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 100, 145));

        jLabelAbajoDcha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Repr Cartas/red_joker.jpg"))); // NOI18N
        jLabelAbajoDcha2.setText("jLabel2");
        jLabelAbajoDcha2.setMaximumSize(new java.awt.Dimension(145, 100));
        jLabelAbajoDcha2.setMinimumSize(new java.awt.Dimension(145, 100));
        jLabelAbajoDcha2.setPreferredSize(new java.awt.Dimension(145, 100));
        jLabelAbajoDcha2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAbajoDcha2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelAbajoDcha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 600, 100, 145));

        jLabelAbajoDcha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Repr Cartas/red_joker.jpg"))); // NOI18N
        jLabelAbajoDcha1.setText("jLabel2");
        jLabelAbajoDcha1.setMaximumSize(new java.awt.Dimension(145, 100));
        jLabelAbajoDcha1.setMinimumSize(new java.awt.Dimension(145, 100));
        jLabelAbajoDcha1.setPreferredSize(new java.awt.Dimension(145, 100));
        jLabelAbajoDcha1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAbajoDcha1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelAbajoDcha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 600, 100, 145));

        jLabelAbajo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Repr Cartas/red_joker.jpg"))); // NOI18N
        jLabelAbajo2.setText("jLabel2");
        jLabelAbajo2.setMaximumSize(new java.awt.Dimension(145, 100));
        jLabelAbajo2.setMinimumSize(new java.awt.Dimension(145, 100));
        jLabelAbajo2.setPreferredSize(new java.awt.Dimension(145, 100));
        jLabelAbajo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAbajo2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelAbajo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 710, 100, 145));

        jLabelAbajo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Repr Cartas/red_joker.jpg"))); // NOI18N
        jLabelAbajo1.setText("jLabel2");
        jLabelAbajo1.setMaximumSize(new java.awt.Dimension(145, 100));
        jLabelAbajo1.setMinimumSize(new java.awt.Dimension(145, 100));
        jLabelAbajo1.setPreferredSize(new java.awt.Dimension(145, 100));
        jLabelAbajo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAbajo1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelAbajo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 710, 100, 145));

        jLabelAbajoIzda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Repr Cartas/red_joker.jpg"))); // NOI18N
        jLabelAbajoIzda2.setText("jLabel2");
        jLabelAbajoIzda2.setMaximumSize(new java.awt.Dimension(145, 100));
        jLabelAbajoIzda2.setMinimumSize(new java.awt.Dimension(145, 100));
        jLabelAbajoIzda2.setPreferredSize(new java.awt.Dimension(145, 100));
        jLabelAbajoIzda2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAbajoIzda2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelAbajoIzda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 100, 145));

        jLabelAbajoIzda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Repr Cartas/red_joker.jpg"))); // NOI18N
        jLabelAbajoIzda1.setText("jLabel2");
        jLabelAbajoIzda1.setMaximumSize(new java.awt.Dimension(145, 100));
        jLabelAbajoIzda1.setMinimumSize(new java.awt.Dimension(145, 100));
        jLabelAbajoIzda1.setPreferredSize(new java.awt.Dimension(145, 100));
        jLabelAbajoIzda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAbajoIzda1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelAbajoIzda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 600, 100, 145));

        jButtonReset.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jButtonReset.setText("RESET");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, 160, 50));

        jButtonAleatorio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonAleatorio.setText("ALEATORIO");
        jButtonAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAleatorioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAleatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 40));

        jButtonPreflop.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonPreflop.setText("PRE-FLOP");
        jButtonPreflop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreflopActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPreflop, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 40));

        jButtonFlop.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonFlop.setText("FLOP");
        jButtonFlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlopActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFlop, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 130, 40));

        jButtonRiver.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonRiver.setText("RIVER");
        jButtonRiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRiverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, 40));

        jButtonTurn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonTurn.setText("TURN");
        jButtonTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTurnActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, 40));

        foldJugArr.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        foldJugArr.setText("FOLD");
        foldJugArr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foldJugArrActionPerformed(evt);
            }
        });
        getContentPane().add(foldJugArr, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, -1, -1));

        foldJugArrIzda.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        foldJugArrIzda.setText("FOLD");
        foldJugArrIzda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foldJugArrIzdaActionPerformed(evt);
            }
        });
        getContentPane().add(foldJugArrIzda, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        foldJugArrDcha.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        foldJugArrDcha.setText("FOLD");
        foldJugArrDcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foldJugArrDchaActionPerformed(evt);
            }
        });
        getContentPane().add(foldJugArrDcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 340, -1, -1));

        foldJugAb.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        foldJugAb.setText("FOLD");
        foldJugAb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foldJugAbActionPerformed(evt);
            }
        });
        getContentPane().add(foldJugAb, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 860, -1, -1));

        foldJugAbIzda.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        foldJugAbIzda.setText("FOLD");
        foldJugAbIzda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foldJugAbIzdaActionPerformed(evt);
            }
        });
        getContentPane().add(foldJugAbIzda, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 750, -1, -1));

        foldJugAbDcha.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        foldJugAbDcha.setText("FOLD");
        foldJugAbDcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foldJugAbDchaActionPerformed(evt);
            }
        });
        getContentPane().add(foldJugAbDcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 750, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo mesa poker.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelArriba1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelArriba1MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionCartas sc = new SeleccionCartas(juegoActual, MainWindow.this, "arr1");
                sc.setVisible(true);
            }

        });

    }//GEN-LAST:event_jLabelArriba1MouseClicked

    public JLabel getjLabelFlop1() {
        return jLabelFlop1;
    }

    public JLabel getjLabelFlop2() {
        return jLabelFlop2;
    }

    public JLabel getjLabelFlop3() {
        return jLabelFlop3;
    }

    private void jButtonAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAleatorioActionPerformed
        // TODO add your handling code here:
        Random rnd = new Random();
        if (juegoActual.getJugArr().getCarta1() == null) {
            int ale = rnd.nextInt(juegoActual.getBaraja().getBaraja().size());
            juegoActual.getJugArr().setCarta1(juegoActual.getBaraja().getBaraja().get(ale));
            juegoActual.getJugArr().getjLabelCarta1().setIcon(new ImageIcon(juegoActual.getBaraja().getBaraja().get(ale).getRutaRep()));
            juegoActual.getBaraja().getBaraja().remove(ale);
        }
        if (juegoActual.getJugArr().getCarta2() == null) {
            int ale = rnd.nextInt(juegoActual.getBaraja().getBaraja().size());
            juegoActual.getJugArr().setCarta2(juegoActual.getBaraja().getBaraja().get(ale));
            juegoActual.getJugArr().getjLabelCarta2().setIcon(new ImageIcon(juegoActual.getBaraja().getBaraja().get(ale).getRutaRep()));
            juegoActual.getBaraja().getBaraja().remove(ale);
        }
        if (juegoActual.getJugArrDcha().getCarta1() == null) {
            int ale = rnd.nextInt(juegoActual.getBaraja().getBaraja().size());
            juegoActual.getJugArrDcha().setCarta1(juegoActual.getBaraja().getBaraja().get(ale));
            juegoActual.getJugArrDcha().getjLabelCarta1().setIcon(new ImageIcon(juegoActual.getBaraja().getBaraja().get(ale).getRutaRep()));
            juegoActual.getBaraja().getBaraja().remove(ale);
        }
        if (juegoActual.getJugArrDcha().getCarta2() == null) {
            int ale = rnd.nextInt(juegoActual.getBaraja().getBaraja().size());
            juegoActual.getJugArrDcha().setCarta2(juegoActual.getBaraja().getBaraja().get(ale));
            juegoActual.getJugArrDcha().getjLabelCarta2().setIcon(new ImageIcon(juegoActual.getBaraja().getBaraja().get(ale).getRutaRep()));
            juegoActual.getBaraja().getBaraja().remove(ale);
        }
        if (juegoActual.getJugArrIzda().getCarta1() == null) {
            int ale = rnd.nextInt(juegoActual.getBaraja().getBaraja().size());
            juegoActual.getJugArrIzda().setCarta1(juegoActual.getBaraja().getBaraja().get(ale));
            juegoActual.getJugArrIzda().getjLabelCarta1().setIcon(new ImageIcon(juegoActual.getBaraja().getBaraja().get(ale).getRutaRep()));
            juegoActual.getBaraja().getBaraja().remove(ale);
        }
        if (juegoActual.getJugArrIzda().getCarta2() == null) {
            int ale = rnd.nextInt(juegoActual.getBaraja().getBaraja().size());
            juegoActual.getJugArrIzda().setCarta2(juegoActual.getBaraja().getBaraja().get(ale));
            juegoActual.getJugArrIzda().getjLabelCarta2().setIcon(new ImageIcon(juegoActual.getBaraja().getBaraja().get(ale).getRutaRep()));
            juegoActual.getBaraja().getBaraja().remove(ale);
        }
        if (juegoActual.getJugAb().getCarta1() == null) {
            int ale = rnd.nextInt(juegoActual.getBaraja().getBaraja().size());
            juegoActual.getJugAb().setCarta1(juegoActual.getBaraja().getBaraja().get(ale));
            juegoActual.getJugAb().getjLabelCarta1().setIcon(new ImageIcon(juegoActual.getBaraja().getBaraja().get(ale).getRutaRep()));
            juegoActual.getBaraja().getBaraja().remove(ale);
        }
        if (juegoActual.getJugAb().getCarta2() == null) {
            int ale = rnd.nextInt(juegoActual.getBaraja().getBaraja().size());
            juegoActual.getJugAb().setCarta2(juegoActual.getBaraja().getBaraja().get(ale));
            juegoActual.getJugAb().getjLabelCarta2().setIcon(new ImageIcon(juegoActual.getBaraja().getBaraja().get(ale).getRutaRep()));
            juegoActual.getBaraja().getBaraja().remove(ale);
        }
        if (juegoActual.getJugAbDcha().getCarta1() == null) {
            int ale = rnd.nextInt(juegoActual.getBaraja().getBaraja().size());
            juegoActual.getJugAbDcha().setCarta1(juegoActual.getBaraja().getBaraja().get(ale));
            juegoActual.getJugAbDcha().getjLabelCarta1().setIcon(new ImageIcon(juegoActual.getBaraja().getBaraja().get(ale).getRutaRep()));
            juegoActual.getBaraja().getBaraja().remove(ale);
        }
        if (juegoActual.getJugAbDcha().getCarta2() == null) {
            int ale = rnd.nextInt(juegoActual.getBaraja().getBaraja().size());
            juegoActual.getJugAbDcha().setCarta2(juegoActual.getBaraja().getBaraja().get(ale));
            juegoActual.getJugAbDcha().getjLabelCarta2().setIcon(new ImageIcon(juegoActual.getBaraja().getBaraja().get(ale).getRutaRep()));
            juegoActual.getBaraja().getBaraja().remove(ale);
        }
        if (juegoActual.getJugAbIzda().getCarta1() == null) {
            int ale = rnd.nextInt(juegoActual.getBaraja().getBaraja().size());
            juegoActual.getJugAbIzda().setCarta1(juegoActual.getBaraja().getBaraja().get(ale));
            juegoActual.getJugAbIzda().getjLabelCarta1().setIcon(new ImageIcon(juegoActual.getBaraja().getBaraja().get(ale).getRutaRep()));
            juegoActual.getBaraja().getBaraja().remove(ale);
        }
        if (juegoActual.getJugAbIzda().getCarta2() == null) {
            int ale = rnd.nextInt(juegoActual.getBaraja().getBaraja().size());
            juegoActual.getJugAbIzda().setCarta2(juegoActual.getBaraja().getBaraja().get(ale));
            juegoActual.getJugAbIzda().getjLabelCarta2().setIcon(new ImageIcon(juegoActual.getBaraja().getBaraja().get(ale).getRutaRep()));
            juegoActual.getBaraja().getBaraja().remove(ale);
        }


    }//GEN-LAST:event_jButtonAleatorioActionPerformed

    private void jButtonPreflopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreflopActionPerformed

        juegoActual.preflop();

        if (!juegoActual.getJugArr().isFold()) {
            juegoActual.getJugArr().setPorcentaje((juegoActual.getJugArr().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugAb().isFold()) {
            juegoActual.getJugAb().setPorcentaje((juegoActual.getJugAb().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugArrDcha().isFold()) {
            juegoActual.getJugArrDcha().setPorcentaje((juegoActual.getJugArrDcha().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugAbDcha().isFold()) {
            juegoActual.getJugAbDcha().setPorcentaje((juegoActual.getJugAbDcha().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugArrIzda().isFold()) {
            juegoActual.getJugArrIzda().setPorcentaje((juegoActual.getJugArrIzda().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugAbIzda().isFold()) {
            juegoActual.getJugAbIzda().setPorcentaje((juegoActual.getJugAbIzda().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }

        if (!juegoActual.getJugArr().isFold()) {
            porcentajeArr.setText("" + juegoActual.getJugArr().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugAb().isFold()) {
            porcentajeAb.setText("" + juegoActual.getJugAb().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugArrDcha().isFold()) {
            porcentajeArrDcha.setText("" + juegoActual.getJugArrDcha().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugArrIzda().isFold()) {
            porcentajeArrIzda.setText("" + juegoActual.getJugArrIzda().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugAbDcha().isFold()) {
            porcentajeAbDcha.setText("" + juegoActual.getJugAbDcha().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugAbIzda().isFold()) {
            porcentajeAbIzda.setText("" + juegoActual.getJugAbIzda().getPorcentaje() + "%");
        }
    }//GEN-LAST:event_jButtonPreflopActionPerformed

    private void jLabelArriba2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelArriba2MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionCartas sc = new SeleccionCartas(juegoActual, MainWindow.this, "arr2");
                sc.setVisible(true);
            }

        });
    }//GEN-LAST:event_jLabelArriba2MouseClicked

    private void jLabelArribaIzda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelArribaIzda1MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionCartas sc = new SeleccionCartas(juegoActual, MainWindow.this, "arrizda1");
                sc.setVisible(true);
            }

        });
    }//GEN-LAST:event_jLabelArribaIzda1MouseClicked

    private void jLabelArribaIzda2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelArribaIzda2MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionCartas sc = new SeleccionCartas(juegoActual, MainWindow.this, "arrizda2");
                sc.setVisible(true);
            }

        });
    }//GEN-LAST:event_jLabelArribaIzda2MouseClicked

    private void jLabelArribaDcha2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelArribaDcha2MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionCartas sc = new SeleccionCartas(juegoActual, MainWindow.this, "arrdcha2");
                sc.setVisible(true);
            }

        });
    }//GEN-LAST:event_jLabelArribaDcha2MouseClicked

    private void jLabelArribaDcha1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelArribaDcha1MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionCartas sc = new SeleccionCartas(juegoActual, MainWindow.this, "arrdcha1");
                sc.setVisible(true);
            }

        });
    }//GEN-LAST:event_jLabelArribaDcha1MouseClicked

    private void jLabelAbajo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAbajo2MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionCartas sc = new SeleccionCartas(juegoActual, MainWindow.this, "ab2");
                sc.setVisible(true);
            }

        });
    }//GEN-LAST:event_jLabelAbajo2MouseClicked

    private void jLabelAbajo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAbajo1MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionCartas sc = new SeleccionCartas(juegoActual, MainWindow.this, "ab1");
                sc.setVisible(true);
            }

        });
    }//GEN-LAST:event_jLabelAbajo1MouseClicked

    private void jLabelAbajoIzda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAbajoIzda1MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionCartas sc = new SeleccionCartas(juegoActual, MainWindow.this, "abizda1");
                sc.setVisible(true);
            }

        });
    }//GEN-LAST:event_jLabelAbajoIzda1MouseClicked

    private void jLabelAbajoIzda2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAbajoIzda2MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionCartas sc = new SeleccionCartas(juegoActual, MainWindow.this, "abizda2");
                sc.setVisible(true);
            }

        });
    }//GEN-LAST:event_jLabelAbajoIzda2MouseClicked

    private void jLabelAbajoDcha2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAbajoDcha2MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionCartas sc = new SeleccionCartas(juegoActual, MainWindow.this, "abdcha2");
                sc.setVisible(true);
            }

        });
    }//GEN-LAST:event_jLabelAbajoDcha2MouseClicked

    private void jLabelAbajoDcha1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAbajoDcha1MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionCartas sc = new SeleccionCartas(juegoActual, MainWindow.this, "abdcha1");
                sc.setVisible(true);
            }

        });
    }//GEN-LAST:event_jLabelAbajoDcha1MouseClicked

    private void jButtonFlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlopActionPerformed
        // TODO add your handling code here:
        juegoActual.flop();
        if (!juegoActual.getJugArr().isFold()) {
            juegoActual.getJugArr().setPorcentaje((juegoActual.getJugArr().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugAb().isFold()) {
            juegoActual.getJugAb().setPorcentaje((juegoActual.getJugAb().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugArrDcha().isFold()) {
            juegoActual.getJugArrDcha().setPorcentaje((juegoActual.getJugArrDcha().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugAbDcha().isFold()) {
            juegoActual.getJugAbDcha().setPorcentaje((juegoActual.getJugAbDcha().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugArrIzda().isFold()) {
            juegoActual.getJugArrIzda().setPorcentaje((juegoActual.getJugArrIzda().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugAbIzda().isFold()) {
            juegoActual.getJugAbIzda().setPorcentaje((juegoActual.getJugAbIzda().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }

        if (!juegoActual.getJugArr().isFold()) {
            porcentajeArr.setText("" + juegoActual.getJugArr().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugAb().isFold()) {
            porcentajeAb.setText("" + juegoActual.getJugAb().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugArrDcha().isFold()) {
            porcentajeArrDcha.setText("" + juegoActual.getJugArrDcha().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugArrIzda().isFold()) {
            porcentajeArrIzda.setText("" + juegoActual.getJugArrIzda().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugAbDcha().isFold()) {
            porcentajeAbDcha.setText("" + juegoActual.getJugAbDcha().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugAbIzda().isFold()) {
            porcentajeAbIzda.setText("" + juegoActual.getJugAbIzda().getPorcentaje() + "%");
        }
    }//GEN-LAST:event_jButtonFlopActionPerformed

    private void jButtonTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTurnActionPerformed
        // TODO add your handling code here:
        juegoActual.turn();

        if (!juegoActual.getJugArr().isFold()) {
            juegoActual.getJugArr().setPorcentaje((juegoActual.getJugArr().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugAb().isFold()) {
            juegoActual.getJugAb().setPorcentaje((juegoActual.getJugAb().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugArrDcha().isFold()) {
            juegoActual.getJugArrDcha().setPorcentaje((juegoActual.getJugArrDcha().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugAbDcha().isFold()) {
            juegoActual.getJugAbDcha().setPorcentaje((juegoActual.getJugAbDcha().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugArrIzda().isFold()) {
            juegoActual.getJugArrIzda().setPorcentaje((juegoActual.getJugArrIzda().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugAbIzda().isFold()) {
            juegoActual.getJugAbIzda().setPorcentaje((juegoActual.getJugAbIzda().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }

        if (!juegoActual.getJugArr().isFold()) {
            porcentajeArr.setText("" + juegoActual.getJugArr().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugAb().isFold()) {
            porcentajeAb.setText("" + juegoActual.getJugAb().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugArrDcha().isFold()) {
            porcentajeArrDcha.setText("" + juegoActual.getJugArrDcha().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugArrIzda().isFold()) {
            porcentajeArrIzda.setText("" + juegoActual.getJugArrIzda().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugAbDcha().isFold()) {
            porcentajeAbDcha.setText("" + juegoActual.getJugAbDcha().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugAbIzda().isFold()) {
            porcentajeAbIzda.setText("" + juegoActual.getJugAbIzda().getPorcentaje() + "%");
        }
    }//GEN-LAST:event_jButtonTurnActionPerformed

    public JLabel getjLabelRiver() {
        return jLabelRiver;
    }

    public JLabel getjLabelTurn() {
        return jLabelTurn;
    }

    private void jButtonRiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRiverActionPerformed
        // TODO add your handling code here:
        juegoActual.river();

        if (!juegoActual.getJugArr().isFold()) {
            juegoActual.getJugArr().setPorcentaje((juegoActual.getJugArr().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugAb().isFold()) {
            juegoActual.getJugAb().setPorcentaje((juegoActual.getJugAb().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugArrDcha().isFold()) {
            juegoActual.getJugArrDcha().setPorcentaje((juegoActual.getJugArrDcha().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugAbDcha().isFold()) {
            juegoActual.getJugAbDcha().setPorcentaje((juegoActual.getJugAbDcha().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugArrIzda().isFold()) {
            juegoActual.getJugArrIzda().setPorcentaje((juegoActual.getJugArrIzda().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }
        if (!juegoActual.getJugAbIzda().isFold()) {
            juegoActual.getJugAbIzda().setPorcentaje((juegoActual.getJugAbIzda().getJugadasGanadas() * 100) / juegoActual.getNumCombinaciones());
        }

        if (!juegoActual.getJugArr().isFold()) {
            porcentajeArr.setText("" + juegoActual.getJugArr().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugAb().isFold()) {
            porcentajeAb.setText("" + juegoActual.getJugAb().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugArrDcha().isFold()) {
            porcentajeArrDcha.setText("" + juegoActual.getJugArrDcha().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugArrIzda().isFold()) {
            porcentajeArrIzda.setText("" + juegoActual.getJugArrIzda().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugAbDcha().isFold()) {
            porcentajeAbDcha.setText("" + juegoActual.getJugAbDcha().getPorcentaje() + "%");
        }
        if (!juegoActual.getJugAbIzda().isFold()) {
            porcentajeAbIzda.setText("" + juegoActual.getJugAbIzda().getPorcentaje() + "%");
        }
    }//GEN-LAST:event_jButtonRiverActionPerformed

    private void foldJugArrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foldJugArrActionPerformed
        // TODO add your handling code here:
        if (juegoActual.getNumJugadores() > 2) {
            juegoActual.getJugArr().setFold(true);
            juegoActual.setNumJugadores(juegoActual.getNumJugadores() - 1);
            porcentajeArr.setText("FOLD");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Pero deja minimo a dos jugadores jugando, atontao",
                    "Mas tonto que las piedras",
                    JOptionPane.ERROR_MESSAGE);
        }
        foldJugArr.setEnabled(false);

    }//GEN-LAST:event_foldJugArrActionPerformed

    private void foldJugAbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foldJugAbActionPerformed
        // TODO add your handling code here:
        if (juegoActual.getNumJugadores() > 2) {
            juegoActual.getJugAb().setFold(true);
            juegoActual.setNumJugadores(juegoActual.getNumJugadores() - 1);
            porcentajeAb.setText("FOLD");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Pero deja minimo a dos jugadores jugando, atontao",
                    "Mas tonto que las piedras",
                    JOptionPane.ERROR_MESSAGE);
        }
        foldJugAb.setEnabled(false);

    }//GEN-LAST:event_foldJugAbActionPerformed

    private void foldJugArrDchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foldJugArrDchaActionPerformed
        // TODO add your handling code here:
        if (juegoActual.getNumJugadores() > 2) {
            juegoActual.getJugArrDcha().setFold(true);
            juegoActual.setNumJugadores(juegoActual.getNumJugadores() - 1);
            porcentajeArrDcha.setText("FOLD");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Pero deja minimo a dos jugadores jugando, atontao",
                    "Mas tonto que las piedras",
                    JOptionPane.ERROR_MESSAGE);
        }
        foldJugArrDcha.setEnabled(false);
    }//GEN-LAST:event_foldJugArrDchaActionPerformed

    private void foldJugArrIzdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foldJugArrIzdaActionPerformed
        // TODO add your handling code here:
        if (juegoActual.getNumJugadores() > 2) {
            juegoActual.getJugArrIzda().setFold(true);
            juegoActual.setNumJugadores(juegoActual.getNumJugadores() - 1);
            porcentajeArrIzda.setText("FOLD");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Pero deja minimo a dos jugadores jugando, atontao",
                    "Mas tonto que las piedras",
                    JOptionPane.ERROR_MESSAGE);
        }
        foldJugArrIzda.setEnabled(false);
    }//GEN-LAST:event_foldJugArrIzdaActionPerformed

    private void foldJugAbDchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foldJugAbDchaActionPerformed
        // TODO add your handling code here:
        if (juegoActual.getNumJugadores() > 2) {
            juegoActual.getJugAbDcha().setFold(true);
            juegoActual.setNumJugadores(juegoActual.getNumJugadores() - 1);
            porcentajeAbDcha.setText("FOLD");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Pero deja minimo a dos jugadores jugando, atontao",
                    "Mas tonto que las piedras",
                    JOptionPane.ERROR_MESSAGE);
        }
        foldJugAbDcha.setEnabled(false);
    }//GEN-LAST:event_foldJugAbDchaActionPerformed

    private void foldJugAbIzdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foldJugAbIzdaActionPerformed
        // TODO add your handling code here:
        if (juegoActual.getNumJugadores() > 2) {
            juegoActual.getJugAbIzda().setFold(true);
            juegoActual.setNumJugadores(juegoActual.getNumJugadores() - 1);
            porcentajeAbIzda.setText("FOLD");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Pero deja minimo a dos jugadores jugando, atontao",
                    "Mas tonto que las piedras",
                    JOptionPane.ERROR_MESSAGE);
        }
        foldJugAbIzda.setEnabled(false);
    }//GEN-LAST:event_foldJugAbIzdaActionPerformed

    private void jLabelFlop1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFlop1MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionCartas sc = new SeleccionCartas(juegoActual, MainWindow.this, "flop1");
                sc.setVisible(true);
            }

        });
    }//GEN-LAST:event_jLabelFlop1MouseClicked

    private void jLabelFlop2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFlop2MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionCartas sc = new SeleccionCartas(juegoActual, MainWindow.this, "flop2");
                sc.setVisible(true);
            }

        });
    }//GEN-LAST:event_jLabelFlop2MouseClicked

    private void jLabelFlop3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFlop3MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionCartas sc = new SeleccionCartas(juegoActual, MainWindow.this, "flop3");
                sc.setVisible(true);
            }

        });
    }//GEN-LAST:event_jLabelFlop3MouseClicked

    private void jLabelTurnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTurnMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionCartas sc = new SeleccionCartas(juegoActual, MainWindow.this, "turn");
                sc.setVisible(true);
            }

        });
    }//GEN-LAST:event_jLabelTurnMouseClicked

    private void jLabelRiverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRiverMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionCartas sc = new SeleccionCartas(juegoActual, MainWindow.this, "river");
                sc.setVisible(true);
            }

        });
    }//GEN-LAST:event_jLabelRiverMouseClicked

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonResetActionPerformed

    public JLabel getjLabelAbajo1() {
        return jLabelAbajo1;
    }

    public JLabel getjLabelAbajo2() {
        return jLabelAbajo2;
    }

    public JLabel getjLabelAbajoDcha1() {
        return jLabelAbajoDcha1;
    }

    public JLabel getjLabelAbajoDcha2() {
        return jLabelAbajoDcha2;
    }

    public JLabel getjLabelAbajoIzda1() {
        return jLabelAbajoIzda1;
    }

    public JLabel getjLabelAbajoIzda2() {
        return jLabelAbajoIzda2;
    }

    public JLabel getjLabelArriba1() {
        return jLabelArriba1;
    }

    public JLabel getjLabelArriba2() {
        return jLabelArriba2;
    }

    public JLabel getjLabelArribaDcha1() {
        return jLabelArribaDcha1;
    }

    public JLabel getjLabelArribaDcha2() {
        return jLabelArribaDcha2;
    }

    public JLabel getjLabelArribaIzda1() {
        return jLabelArribaIzda1;
    }

    public JLabel getjLabelArribaIzda2() {
        return jLabelArribaIzda2;
    }

    public Baraja getBaraja() {
        return this.juegoActual.getBaraja();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton foldJugAb;
    private javax.swing.JButton foldJugAbDcha;
    private javax.swing.JButton foldJugAbIzda;
    private javax.swing.JButton foldJugArr;
    private javax.swing.JButton foldJugArrDcha;
    private javax.swing.JButton foldJugArrIzda;
    private javax.swing.JButton jButtonAleatorio;
    private javax.swing.JButton jButtonFlop;
    private javax.swing.JButton jButtonPreflop;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonRiver;
    private javax.swing.JButton jButtonTurn;
    private javax.swing.JLabel jLabelAbajo1;
    private javax.swing.JLabel jLabelAbajo2;
    private javax.swing.JLabel jLabelAbajoDcha1;
    private javax.swing.JLabel jLabelAbajoDcha2;
    private javax.swing.JLabel jLabelAbajoIzda1;
    private javax.swing.JLabel jLabelAbajoIzda2;
    private javax.swing.JLabel jLabelArriba1;
    private javax.swing.JLabel jLabelArriba2;
    private javax.swing.JLabel jLabelArribaDcha1;
    private javax.swing.JLabel jLabelArribaDcha2;
    private javax.swing.JLabel jLabelArribaIzda1;
    private javax.swing.JLabel jLabelArribaIzda2;
    private javax.swing.JLabel jLabelFlop1;
    private javax.swing.JLabel jLabelFlop2;
    private javax.swing.JLabel jLabelFlop3;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelRiver;
    private javax.swing.JLabel jLabelTurn;
    private javax.swing.JLabel porcentajeAb;
    private javax.swing.JLabel porcentajeAbDcha;
    private javax.swing.JLabel porcentajeAbIzda;
    private javax.swing.JLabel porcentajeArr;
    private javax.swing.JLabel porcentajeArrDcha;
    private javax.swing.JLabel porcentajeArrIzda;
    // End of variables declaration//GEN-END:variables
}
